# Site
repository: reza-shkv97/reza-shkv97.github.io
#favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Reza Shirkavand
title: Software Engineering Student at Sharif University of Technology, Tehran, Iran.
email: rezashirkavand1997@gmail.com
website: https://github.com/reza-shkv97/

# Dark Mode (true/false/never)
darkmode: True

# Social links
twitter_username: reza_shkv
github_username:  reza-shkv97
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: reza_shkv
linkedin_username: reza-shirkavand-3b508612b
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: google_scholar
  icon: ai ai-google-scholar-square
  url: https://scholar.google.com/citations?user=uS4nCAMAAAAJ&hl=en
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile2.jpg
about_content: | # this will include new lines to allow paragraphs
  My name is Reza Shirkavand and I'm a Software Engineering B.Sc. graduate from Sharif University of Technology. I am currently a Data Scientist at Netbina Advertising Agency.
  My Research Interests are Machine Learning, Deep Learning, Computer Vision, Medical Image Analysis, and Optimization.

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Sharif University of Technology
        link: www.sharif.edu
        caption: 2015 - 2020
        sub_title: B.Sc. Software Engineering
        quote: >
          Established in 1966, Sharif University of Technology is widely considered as the Iran's leading institution for science, technology, engineering, and mathematics (STEM) fields.
        description: | # this will include new lines to allow paragraphs
          Some passed and audited courses:
          Artificial Intelligence, Machine Learning, Deep Learning, Statistical Learning
          Modern Information Retrieval, Signals and Systems, Algorithmic Game Theory, Linear Algebra, Convex Optimization

  - title: Research Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Research Assistant, Medical Image Processing
        caption: 2019 - Present
        quote: >
          Supervisors: Prof Hamid R. Rabiee and Dr. Mohammad Hossein Rohban
        description: | # this will include new lines to allow paragraphs
          The research aims at the classification of visual biomarkers of dementia based on Fazekas Scale. The aforementioned biomarkers are Periventricular White Matter(PVWM) Changes and Deep White Matter (DWM) Changes.

  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: ”Dementia Severity Clas- sification under Small Sample Size and Weak Supervision in Thick Slice MRI”
        caption: R. Shirkavand, S. Farghadani, S. Ayromlou, M. S Tahaei, F.Pourakpour, B. Siahlou, Z. Kho- dakarami, M. H. Rohban, M. Fatehi, M. H. Rohban, H. R. Rabiee
        link: https://arxiv.org/abs/2103.10056
        link_text: Manuscript Preprint
        additional_links:
          - title: dementia-classification/Dementia-Severity-Classification
            icon: fab fa-github
            url: https://github.com/dementia-classification/Dementia-Severity-Classification


  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Netbina Advertising Agency
        link: https://www.netbina.com
        # link_text: boringcompany.com
        sub_title: Senior Data Scientist
        caption: February 2020 - Present
        quote: >
          in-house, inter-related service offerings and help to provide an integrated solution to clients in shaping their strategy and communication.
        description: | # this will include new lines to allow paragraphs
            Developing Computer Vision and Natural Language Processing models in order to monitor, organize, and manage brands online reputation all in one platform.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Cycling
      - Gaming
      - Football (Soccer!)
      - Travel

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
